# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49aa7b4908d816f109abcc8e345b643d39a6f2c1f259ef3c3d96f4d4e4cef041a6d31f92c4c3dd9aaa655103daa8a7eaa712b9c8e0585435e265a94dd416178d

test:
  secret_key_base: 8bcee73ea8be910057431accc3f03aa072f2d0e8b45a8de5e471ee2f52d8c03a59ebe52f4dbbff1eaa52146b58a0b49f1a15b3f882699e61c6b72efd0f599f19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
